version: 2.1

jobs:
  build-ios:
    macos:
      xcode: 15.3.0
    steps:
      - checkout
      - run:
          name: Install Flutter
          command: |
            git clone https://github.com/flutter/flutter.git -b stable
            export PATH="$PATH:`pwd`/flutter/bin"
            flutter doctor
      - run:
          name: Build IPA
          command: |
            export PATH="$PATH:`pwd`/flutter/bin"
            flutter build ipa --no-codesign

workflows:
  build:
    jobs:
      - build-ios
