version: 2.1

jobs:
  build-ios:
    macos:
      xcode: 15.3.0
    steps:
      - checkout
      - run:
          name: Install Flutter
          command: |
            git clone https://github.com/flutter/flutter.git -b stable
            export PATH="$PATH:`pwd`/flutter/bin"
            flutter doctor
      - run:
          name: Disable Signing
          command: |
            cd ios
            sed -i '' 's/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = com.example.telebirr;/' Runner.xcodeproj/project.pbxproj
            sed -i '' 's/CODE_SIGN_STYLE = Automatic/CODE_SIGN_STYLE = Manual/' Runner.xcodeproj/project.pbxproj
            sed -i '' 's/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = "";/' Runner.xcodeproj/project.pbxproj
      - run:
          name: Build iOS
          command: |
            export PATH="$PATH:`pwd`/flutter/bin"
            flutter build ios --no-codesign --release

workflows:
  build:
    jobs:
      - build-ios
